@startuml

class Student {
    name
    email
}

class Professor {
    name
}

class Course {
    subject
    professor
    students[ ]
    addStudent(student)
}


Course *--> Professor
Course *--> Student

@enduml